name: Postman API Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run-postman-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install Newman
        run: npm install -g newman

      - name: Run Postman collection
        run: |
          newman run Task_1.postman_collection.json \
          --reporters cli,json \
          --reporter-json-export postman/results.json
